# AUTOGENERATED! DO NOT EDIT! File to edit: ../export_demo.ipynb.

# %% auto 0
__all__ = ['sum']

# %% ../export_demo.ipynb 1
import numpy as np

# %% ../export_demo.ipynb 2
def sum(num1, num2):
     return num1+num2
