# AUTOGENERATED! DO NOT EDIT! File to edit: ../../abid/utils.ipynb.

# %% auto 0
__all__ = ['set_to_our_gpus', 'print_gpu_used_torch', 'enable_web_access', 'change_to_project_dir', 'print_cwd']

# %% ../../abid/utils.ipynb 1
import os

# %% ../../abid/utils.ipynb 2
def set_to_our_gpus(gpu_str="2,3"):
    os.environ['CUDA_VISIBLE_DEVICES'] = gpu_str

# %% ../../abid/utils.ipynb 3
def print_gpu_used_torch():
    ngpu = torch.cuda.device_count()
    for gpu_id in range(ngpu):
        gpu = torch.cuda.get_device_name(gpu_id)
        print(f"GPU:{gpu_id} {gpu}")

# %% ../../abid/utils.ipynb 4
def enable_web_access():
    os.environ['HTTP_PROXY'] = 'http://fp.cs.ovgu.de:3210/'
    os.environ['HTTPS_PROXY'] = 'http://fp.cs.ovgu.de:3210/'

# %% ../../abid/utils.ipynb 5
def change_to_project_dir(subdir="abid"):
    os.chdir(os.path.join(os.path.expanduser("~") , "project/validating_attribution_techniques/" + subdir))

def print_cwd():
    for content in os.listdir(os.getcwd()):
        print(content)
