# AUTOGENERATED! DO NOT EDIT! File to edit: ../../abid/api_notebooks/vit_load.ipynb.

# %% auto 0
__all__ = ['load_vit']

# %% ../../abid/api_notebooks/vit_load.ipynb 1
import torch

# %% ../../abid/api_notebooks/vit_load.ipynb 2
def load_vit(use_cuda=True):
    """
    Loads DeiT tiny distilled model which accepts image size of 224 x 224
    
    input :
      - use_cuda : bool (Optional boolean indicating the main processor being used, either cuda or cpu)
      
    return :
      - vit_distilled_model : function (DeiT tiny model)
    """
    device = torch.device("cuda" if use_cuda else "cpu")
    vit_distilled_model = torch.hub.load('facebookresearch/deit:main', "deit_tiny_distilled_patch16_224", pretrained=True).to(device)
    vit_distilled_model.eval()
    return vit_distilled_model
